# Generated by Django 5.1.6 on 2025-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_route', '0003_alter_trip_schedule_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='schedule',
            name='trip_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
